name: run install script

on:
  # allows us to run workflows manually
  workflow_dispatch:
  push:
    paths:
      - 'scripts/ubuntu.sh'
      - '.github/workflows/install_script.yml'

jobs:
  run_install_script:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        branch: ['develop', 'stable'] # 'develop' can be anything that's not 'stable'. This triggers an if statement in ubuntu.sh
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: run install script
        shell: bash -l {0}
        run: |
          cd $GITHUB_WORKSPACE/scripts
          chmod +x ubuntu.sh
          ./ubuntu.sh ${{ matrix.branch }}

      # use matrix to have 2 jobs [develop, stable]
      # ./ubuntu.sh stable

